"""
Import general Australian foods from the FSANZ Australian Food Composition Database (Release 3).

1. Download the Excel files from foodstandards.gov.au (accept the FSANZ licence: it's based on
   CC BY-SA, so credit FSANZ and share any redistributed version of the data under the same terms).
2. Put the "Food Details" and "Nutrient profiles" files in ./afcd/
3. pip install pandas openpyxl && python scripts/import-afcd.py
Writes lib/data/foods.generated.ts. Column names are matched loosely and printed, so if FSANZ renames
a column the script tells you what it found instead of silently writing bad data.
"""
import glob, json, re, sys
import pandas as pd

# Foods to include: (search phrase in AFCD name, display name, serving label, serving grams)
WANTED = [
    ("chicken, breast, lean flesh, baked", "Chicken breast, baked", "150g", 150),
    ("egg, chicken, whole, boiled", "Egg, boiled", "1 large egg (50g)", 50),
    ("yoghurt, greek style, plain", "Greek-style yoghurt, plain", "170g tub", 170),
    ("tuna, canned in brine, drained", "Tuna in brine, drained", "95g can", 95),
    ("beef, mince, regular fat, cooked", "Beef mince, cooked", "100g", 100),
    ("cheese, cottage", "Cottage cheese", "100g", 100),
    ("milk, cow, fluid, regular fat", "Milk, full cream", "250ml glass", 258),
    ("tofu", "Tofu, firm", "100g", 100),
    ("lentil, dried, boiled", "Lentils, boiled", "1 cup (200g)", 200),
    ("breakfast cereal, whole wheat, biscuits", "Wheat biscuit cereal", "2 biscuits (30g)", 30),
]

def find(frames, *needles):
    for df in frames:
        for col in df.columns:
            if all(n.lower() in str(col).lower() for n in needles):
                return df, col
    sys.exit(f"Couldn't find a column containing {needles}. Columns seen: {[list(f.columns) for f in frames]}")

frames = [pd.read_excel(f) for f in glob.glob("afcd/*.xlsx")]
if not frames: sys.exit("No .xlsx files in ./afcd/")
names_df, name_col = find(frames, "food name") if any("food name" in str(c).lower() for f in frames for c in f.columns) else find(frames, "name")
_, key_col = find([names_df], "key")
nut_df, prot_col = find(frames, "protein")
_, kj_col = find([nut_df], "energy", "kj")
_, nkey_col = find([nut_df], "key")
print("Using:", name_col, prot_col, kj_col)

merged = names_df[[key_col, name_col]].merge(nut_df[[nkey_col, prot_col, kj_col]], left_on=key_col, right_on=nkey_col)
out = []
for phrase, label, serving, grams in WANTED:
    hit = merged[merged[name_col].str.lower().str.contains(re.escape(phrase.lower()), na=False)]
    if hit.empty: print("NOT FOUND, skipped:", phrase); continue
    row = hit.iloc[0]
    p100, kj100 = float(row[prot_col]), float(row[kj_col])
    out.append(dict(id="afcd-" + re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-"), chain="afcd", name=label,
                    category="Everyday foods", serving=serving, grams=grams, protein=round(p100 * grams / 100, 1),
                    kj=round(kj100 * grams / 100), kcal=round(kj100 * grams / 100 / 4.184), afcdKey=str(row[key_col]),
                    afcdName=str(row[name_col])))
    print(f"{label}: {out[-1]['protein']}g protein per {serving}  <- {row[name_col]}")

open("lib/data/foods.generated.ts", "w").write(
    "// Generated by scripts/import-afcd.py from FSANZ AFCD Release 3. Source: Food Standards Australia New Zealand.\n"
    "export const afcdFoods = " + json.dumps(out, indent=2) + " as const;\n")
print(f"Wrote {len(out)} foods. Check each matched AFCD name above before publishing.")
